export const CATEGORIES = [
  {
    id: 'veg',
    name: 'Fresh Vegetables',
    icon: '🥦',
    itemCount: '45+ Items',
    color: '#e8f5e9',
    textColor: '#2e7d32',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'fruits',
    name: 'Organic Fruits',
    icon: '🍎',
    itemCount: '38+ Items',
    color: '#fff3e0',
    textColor: '#e65100',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dairy',
    name: 'Dairy & Eggs',
    icon: '🥛',
    itemCount: '25+ Items',
    color: '#e1f5fe',
    textColor: '#0277bd',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bakery',
    name: 'Bakery & Bread',
    icon: '🍞',
    itemCount: '20+ Items',
    color: '#fff8e1',
    textColor: '#f57f17',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'beverages',
    name: 'Cold Drinks & Juices',
    icon: '🧃',
    itemCount: '30+ Items',
    color: '#f3e5f5',
    textColor: '#7b1fa2',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'meat',
    name: 'Meat & Seafood',
    icon: '🥩',
    itemCount: '18+ Items',
    color: '#ffebee',
    textColor: '#c62828',
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'pantry',
    name: 'Pantry Essentials',
    icon: '🌾',
    itemCount: '50+ Items',
    color: '#efebe9',
    textColor: '#4e342e',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'snacks',
    name: 'Snacks & Munchies',
    icon: '🍿',
    itemCount: '35+ Items',
    color: '#fffde7',
    textColor: '#fbc02d',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=600&q=80',
  },
]

export const PRODUCTS = [
  {
    id: 'p1',
    name: 'Organic Farm Fresh Broccoli',
    category: 'veg',
    categoryName: 'Fresh Vegetables',
    price: 3.49,
    originalPrice: 4.99,
    rating: 4.8,
    reviewCount: 124,
    weight: '500g',
    weightOptions: ['250g', '500g', '1kg'],
    inStock: true,
    stockCount: 45,
    isOrganic: true,
    isFeatured: true,
    isBestSeller: true,
    badge: '20% OFF',
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Locally grown 100% organic broccoli packed with antioxidants, vitamin C, and fiber. Handpicked daily from pesticide-free farms.',
    nutrition: {
      calories: '34 kcal',
      protein: '2.8g',
      carbs: '6.6g',
      fat: '0.4g',
      fiber: '2.6g',
    },
    origin: 'California Green Farms',
  },
  {
    id: 'p2',
    name: 'Fresh Red Hass Avocados',
    category: 'fruits',
    categoryName: 'Organic Fruits',
    price: 4.99,
    originalPrice: 6.49,
    rating: 4.9,
    reviewCount: 210,
    weight: '3 pcs',
    weightOptions: ['2 pcs', '3 pcs', '6 pcs'],
    inStock: true,
    stockCount: 30,
    isOrganic: true,
    isFeatured: true,
    isBestSeller: true,
    badge: 'SUPER DEAL',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1601039641847-7857b994d704?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Creamy, rich Hass avocados rich in healthy monounsaturated fats. Perfectly ripe and ready for guacamole, salads, or avocado toast.',
    nutrition: {
      calories: '160 kcal',
      protein: '2.0g',
      carbs: '8.5g',
      fat: '14.7g',
      fiber: '6.7g',
    },
    origin: 'Michoacán Organic Orchard',
  },
  {
    id: 'p3',
    name: 'Sweet Crisp Organic Strawberries',
    category: 'fruits',
    categoryName: 'Organic Fruits',
    price: 3.99,
    originalPrice: 5.29,
    rating: 4.7,
    reviewCount: 98,
    weight: '400g pack',
    weightOptions: ['250g', '400g pack'],
    inStock: true,
    stockCount: 22,
    isOrganic: true,
    isFeatured: true,
    isBestSeller: false,
    badge: 'FRESH PICK',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Plump, juicy berries rich in sweetness and natural aroma. Perfect for breakfast bowls, smoothies, or fresh snacking.',
    nutrition: {
      calories: '32 kcal',
      protein: '0.7g',
      carbs: '7.7g',
      fat: '0.3g',
      fiber: '2.0g',
    },
    origin: 'Watsonville Berry Farms',
  },
  {
    id: 'p4',
    name: 'Farm Fresh Whole Milk 3.25%',
    category: 'dairy',
    categoryName: 'Dairy & Eggs',
    price: 2.89,
    originalPrice: 3.49,
    rating: 4.6,
    reviewCount: 175,
    weight: '1 Liter',
    weightOptions: ['500ml', '1 Liter', '2 Liter'],
    inStock: true,
    stockCount: 50,
    isOrganic: false,
    isFeatured: false,
    isBestSeller: true,
    badge: null,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Pure, pasteurized farm fresh whole milk with rich creaminess and essential calcium, vitamin D, and proteins.',
    nutrition: {
      calories: '149 kcal',
      protein: '7.7g',
      carbs: '11.7g',
      fat: '7.9g',
      calcium: '276mg',
    },
    origin: 'Valley Creamery Dairies',
  },
  {
    id: 'p5',
    name: 'Artisanal Sourdough Whole Bread',
    category: 'bakery',
    categoryName: 'Bakery & Bread',
    price: 4.49,
    originalPrice: 5.49,
    rating: 4.8,
    reviewCount: 88,
    weight: '500g loaf',
    weightOptions: ['500g loaf', '750g loaf'],
    inStock: true,
    stockCount: 15,
    isOrganic: true,
    isFeatured: true,
    isBestSeller: false,
    badge: 'DAILY BAKED',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Slow-fermented sourdough bread crafted with organic unbleached flour, wild yeast starter, and sea salt. Crispy crust, airy texture.',
    nutrition: {
      calories: '185 kcal',
      protein: '6.0g',
      carbs: '36.0g',
      fat: '1.2g',
      fiber: '2.5g',
    },
    origin: 'Golden Wheat Bakery',
  },
  {
    id: 'p6',
    name: 'Cold Pressed Organic Orange Juice',
    category: 'beverages',
    categoryName: 'Cold Drinks & Juices',
    price: 3.79,
    originalPrice: 4.49,
    rating: 4.7,
    reviewCount: 142,
    weight: '750ml bottle',
    weightOptions: ['500ml', '750ml bottle', '1.5L'],
    inStock: true,
    stockCount: 28,
    isOrganic: true,
    isFeatured: false,
    isBestSeller: true,
    badge: '100% PURE',
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      '100% pure cold-pressed Valencia orange juice without added sugar, preservatives, or artificial concentrates.',
    nutrition: {
      calories: '110 kcal',
      protein: '2.0g',
      carbs: '26.0g',
      fat: '0.0g',
      vitaminC: '120%',
    },
    origin: 'Sunshine Citrus Orchards',
  },
  {
    id: 'p7',
    name: 'Organic Vine-Ripened Cherry Tomatoes',
    category: 'veg',
    categoryName: 'Fresh Vegetables',
    price: 2.99,
    originalPrice: 3.99,
    rating: 4.6,
    reviewCount: 67,
    weight: '300g box',
    weightOptions: ['300g box', '500g box'],
    inStock: true,
    stockCount: 35,
    isOrganic: true,
    isFeatured: false,
    isBestSeller: false,
    badge: 'HOT SALE',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Sweet, juicy cherry tomatoes picked fresh on the vine. Ideal for roasting, salads, pasta dishes, or healthy snacking.',
    nutrition: {
      calories: '27 kcal',
      protein: '1.3g',
      carbs: '5.8g',
      fat: '0.3g',
      fiber: '1.8g',
    },
    origin: 'Greenhouse Organics',
  },
  {
    id: 'p8',
    name: 'Premium Wild Catch Salmon Fillet',
    category: 'meat',
    categoryName: 'Meat & Seafood',
    price: 12.99,
    originalPrice: 15.99,
    rating: 4.9,
    reviewCount: 160,
    weight: '400g',
    weightOptions: ['250g', '400g', '800g'],
    inStock: true,
    stockCount: 18,
    isOrganic: true,
    isFeatured: true,
    isBestSeller: true,
    badge: 'SAVE $3',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Sustainably caught Alaskan wild salmon fillets rich in Omega-3 fatty acids. Skin-on, boneless, and vacuum sealed for peak freshness.',
    nutrition: {
      calories: '206 kcal',
      protein: '22.0g',
      carbs: '0.0g',
      fat: '12.0g',
      omega3: '2.5g',
    },
    origin: 'Alaskan Waters Fishery',
  },
  {
    id: 'p9',
    name: 'Extra Virgin Italian Olive Oil',
    category: 'pantry',
    categoryName: 'Pantry Essentials',
    price: 9.49,
    originalPrice: 11.99,
    rating: 4.8,
    reviewCount: 112,
    weight: '500ml',
    weightOptions: ['500ml', '1 Liter'],
    inStock: true,
    stockCount: 40,
    isOrganic: true,
    isFeatured: false,
    isBestSeller: true,
    badge: null,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'First cold-pressed extra virgin olive oil imported directly from Tuscany. Peppery finish with delicate fruity aroma.',
    nutrition: {
      calories: '120 kcal per tbsp',
      fat: '14.0g',
      saturatedFat: '2.0g',
    },
    origin: 'Tuscany Estates, Italy',
  },
  {
    id: 'p10',
    name: 'Crunchy Roasted Almond & Honey Granola',
    category: 'snacks',
    categoryName: 'Snacks & Munchies',
    price: 5.29,
    originalPrice: 6.49,
    rating: 4.7,
    reviewCount: 85,
    weight: '350g pack',
    weightOptions: ['350g pack', '700g pack'],
    inStock: true,
    stockCount: 25,
    isOrganic: true,
    isFeatured: true,
    isBestSeller: false,
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1517093157656-b9ecedd173a3?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517093157656-b9ecedd173a3?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Handcrafted oat granola baked with raw wild honey, sliced California almonds, chia seeds, and real vanilla bean.',
    nutrition: {
      calories: '210 kcal',
      protein: '6.0g',
      carbs: '28.0g',
      fat: '8.0g',
      fiber: '4.5g',
    },
    origin: 'Nature Bite Foods',
  },
  {
    id: 'p11',
    name: 'Organic Free Range Brown Eggs',
    category: 'dairy',
    categoryName: 'Dairy & Eggs',
    price: 3.99,
    originalPrice: 4.79,
    rating: 4.9,
    reviewCount: 240,
    weight: '12 pcs carton',
    weightOptions: ['6 pcs carton', '12 pcs carton'],
    inStock: true,
    stockCount: 60,
    isOrganic: true,
    isFeatured: false,
    isBestSeller: true,
    badge: 'BEST SELLER',
    image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Eggs from pasture-raised, free-roasting hens fed an organic non-GMO diet. Deep golden yolks rich in Omega-3 and Vitamin E.',
    nutrition: {
      calories: '70 kcal',
      protein: '6.0g',
      fat: '5.0g',
      cholesterol: '185mg',
    },
    origin: 'Sunny Pastures Farm',
  },
  {
    id: 'p12',
    name: 'Fresh Crisp Japanese Cucumber',
    category: 'veg',
    categoryName: 'Fresh Vegetables',
    price: 1.79,
    originalPrice: 2.29,
    rating: 4.5,
    reviewCount: 52,
    weight: '500g',
    weightOptions: ['500g', '1kg'],
    inStock: true,
    stockCount: 40,
    isOrganic: false,
    isFeatured: false,
    isBestSeller: false,
    badge: null,
    image: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=600&q=80',
    ],
    description:
      'Thin-skinned, seedless Japanese cucumbers with crunchy bite and hydrating refreshing taste. Great for salads and tzatziki.',
    nutrition: {
      calories: '15 kcal',
      protein: '0.7g',
      carbs: '3.6g',
      fat: '0.1g',
    },
    origin: 'Pacific Valley Hydroponics',
  },
]

export const HERO_SLIDES = [
  {
    id: 1,
    title: 'Farm Fresh Organic Vegetables Delivered in 30 Mins',
    subtitle: 'Get up to 30% OFF on your first grocery basket order!',
    badge: '100% ORGANIC & LOCAL',
    bgGradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)',
    ctaText: 'Shop Fresh Produce',
    linkCategory: 'veg',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 2,
    title: 'Super Juicy Seasonal Fruits Harvest Sale',
    subtitle: 'Packed with vitamins, handpicked at peak ripeness everyday.',
    badge: 'DAILY HARVEST',
    bgGradient: 'linear-gradient(135deg, #e65100 0%, #ff9800 100%)',
    ctaText: 'Explore Fruits',
    linkCategory: 'fruits',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 3,
    title: 'Artisanal Bakery & Fresh Dairy Delights',
    subtitle: 'Sourdough, fresh churned butter, and pasture-raised eggs.',
    badge: 'BAKED TODAY',
    bgGradient: 'linear-gradient(135deg, #4e342e 0%, #8d6e63 100%)',
    ctaText: 'Order Bakery',
    linkCategory: 'bakery',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
  },
]

export const COUPONS = [
  {
    code: 'FRESH20',
    discountType: 'percentage',
    discountValue: 20,
    minOrder: 15,
    description: '20% Off on orders above $15',
  },
  {
    code: 'FREESHIP',
    discountType: 'shipping',
    discountValue: 100,
    minOrder: 25,
    description: 'Free Express Shipping on orders above $25',
  },
  {
    code: 'ORGANIC10',
    discountType: 'fixed',
    discountValue: 5,
    minOrder: 30,
    description: '$5 Instant discount on organic orders above $30',
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Sarah Jenkins',
    role: 'Verified Customer',
    rating: 5,
    comment:
      'FreshCart has completely changed how I buy groceries! The broccoli and avocados arrived super fresh within 25 minutes. Love the clean app experience.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 2,
    name: 'David Miller',
    role: 'Home Chef',
    rating: 5,
    comment:
      'The wild salmon and artisan sourdough bread quality is unbeatable. Feels like shopping at a high-end farmers market from home.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 3,
    name: 'Elena Rostova',
    role: 'Fitness Trainer',
    rating: 5,
    comment:
      'I order cold-pressed juices and organic eggs weekly. Everything is packed nicely with ice bags and customer support is top tier.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },
]
